# Generated by Django 5.1.2 on 2024-10-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='before_meal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
